version: "3.9"

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deno
      PGPORT: 5432
    networks:
      - tests
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      retries: 5
      start_period: 5s
      timeout: 5s
  backend:
    build: .
    command: deno task test:e2e
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/deno"
    networks:
      - tests
    depends_on:
      database:
        condition: service_healthy

networks:
  tests:
